/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gail;

import gail.Resources.Block;
import gail.Resources.Robot;
import gail.Resources.Target;
import gail.animations.*;
import gail.executors.ActionLoop;
import gail.executors.ActionSequence;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author eneko
 */
public class ExampleFrame extends javax.swing.JFrame {

    /**
     * Creates an ExampleFrame
     */
    public ExampleFrame() {
        initComponents();

        // Create an 8x8 grid.
        Grid g = new Grid(8, 8);
        g.setBackground(Color.white);
        g.setForeground(Color.lightGray);
        this.setContentPane(g);
        this.setMinimumSize(new Dimension(700, 700));

        // Create an element and define actions on them.
        GridElement elem = new GridElement(Resources.getRobot(Robot.BLUE));
        elem.defineAction("moveRight", new MoveRightAnimation());
        elem.defineAction("moveLeft", new MoveLeftAnimation());
        elem.defineAction("moveDown", new MoveDownAnimation());
        elem.defineAction("moveUp", new MoveUpAnimation());

        // Add it to the grid in (1,1).
        g.add(elem, new Point(1,1));
        elem.setPositionOnGrid(new Point(6,6));
        // Create an ActionSequence to execute some actions on the element
        // sequentially, with an initial delay of 500ms.
        ActionSequence actions = new ActionSequence(500);
        actions.execute(elem, "moveRight");
        actions.execute(elem, "moveRight");
        actions.execute(elem, "moveDown");
        actions.execute(elem, "moveDown");
        actions.execute(elem, "moveLeft");
        actions.execute(elem, "moveLeft");
        actions.execute(elem, "moveUp");
        actions.execute(elem, "moveUp");

        // Create and add another element to the grid, and
        // animate it with another ActionSequence, so it will run
        // concurrently with the previously created ActionSequence.
        GridElement elem2 = new GridElement(Resources.getRobot(Robot.RED));
        g.add(elem2, new Point(4,4));
        elem2.defineAction("moveRight", new MoveRightAnimation());
        elem2.defineAction("moveLeft", new MoveLeftAnimation());
        elem2.defineAction("moveDown", new MoveDownAnimation());
        elem2.defineAction("moveUp", new MoveUpAnimation());
        ActionSequence actions2 = new ActionSequence(500);
        actions2.execute(elem2, "moveRight");
        actions2.execute(elem2, "moveRight");
        actions2.execute(elem2, "moveDown");
        actions2.execute(elem2, "moveDown");
        actions2.execute(elem2, "moveLeft");
        actions2.execute(elem2, "moveLeft");
        actions2.execute(elem2, "moveUp");
        actions2.execute(elem2, "moveUp");
        
        // Some elements more, this time static and without actions.
        GridElement elem3 = new GridElement(Resources.getBlock(Block.GRAY));
        GridElement elem4 = new GridElement(Resources.getBlock(Block.GRAY));
        g.add(elem3, new Point(2,2));
        g.add(elem4, new Point(5, 5));
        
        // We are going to add some elements more, this time with "Target"
        // look.
        GridElement elem5 = new GridElement(Resources.getTarget(Target.GRAY));
        GridElement elem6 = new GridElement(Resources.getTarget(Target.GRAY));
        elem5.defineAction("blink", new BlinkAnimation());
        elem6.defineAction("blink", new BlinkAnimation());
        g.add(elem5, new Point(1,1));
        g.add(elem6, new Point(4,4));
        
        // Now, ¿why not make them blink a little? With ActionLoop, you can
        // make the same that you could with ActionSequence but repeat it "n"
        // times or indefinitely, if "loops" parameter = 0.
        ActionLoop actions3 = new ActionLoop(500, 0);
        actions3.execute(elem5, "blink");
        actions3.loop();
        
        // We use two ActionLoops because we want them to run concurrently and
        // not sequentially
        ActionLoop actions4 = new ActionLoop(500, 0);
        actions4.execute(elem6, "blink");
        actions4.loop();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExampleFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
